baseurl = "https://www.oscardc.com/"
title = "Oscar D. Corbalan"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  description = "Computer Engineer from Barcelona that loves challenges. Polyglot with fluency in a dozen programming languages and the skill to quickly pick new ones."
  copyright = "&copy;2019 Oscar D. Corbalan"

  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "you@yoursite.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  mainSections = ["project"]
  professionalSections = ["professional"]  

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/"
  home = true

  [[params.navlinks]]
  name = "About me"
  url = "about/"

  [[params.navlinks]]
  name = "Contact"
  url = "contact/"

  [params.social]
  #facebook      = "full page or profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  email         = "oscardc@gmx.com"
  #twitter       = "oscardcorbalan"
  linkedin      = "oscardc"
  #stackoverflow = "full profile url in stackoverflow"
  #instagram     = "full profile url in instagram"
  npm           = "oscardcorbalan"
  github        = "OscarDCorbalan"
  #gravatar      = "oscardcorbalan"
  #youtube       = "full profile url in youtube"
  #whatsapp      = "wa.me service link"
