name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download hugo
        run: wget https://github.com/gohugoio/hugo/releases/download/v0.75.1/hugo_extended_0.75.1_Linux-64bit.deb
      - name: Install hugo
        run: sudo dpkg -i hugo_extended_0.75.1_Linux-64bit.deb
      - name: Build
        run: hugo --minify
